spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}

server.port=${SERVER_PORT:8081}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false