spring.application.name=servico-movimentacao
server.port=8081

spring.datasource.url=jdbc:h2:mem:movimentacao_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
