server.port=${SERVER_PORT:8080}

# Banco de produção - MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/estoque_principal}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Console H2 desabilitado em produção
spring.h2.console.enabled=false

# Serviço de movimentação
servico.movimentacao.url=${SERVICO_COMUNICACAO_URL}

# OpenFeign
spring.cloud.openfeign.client.config.movimentacao-service.connect-timeout=${FEIGN_CONNECT_TIMEOUT:2000}
spring.cloud.openfeign.client.config.movimentacao-service.read-timeout=${FEIGN_READ_TIMEOUT:3000}