server.port=${SERVER_PORT:8080}

# Banco de desenvolvimento - H2
spring.datasource.url=${DB_URL:jdbc:h2:mem:estoque_principal}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Serviço de movimentação
servico.movimentacao.url=${SERVICO_COMUNICACAO_URL:http://localhost:8081}

# OpenFeign
spring.cloud.openfeign.client.config.movimentacao-service.connect-timeout=${FEIGN_CONNECT_TIMEOUT:2000}
spring.cloud.openfeign.client.config.movimentacao-service.read-timeout=${FEIGN_READ_TIMEOUT:3000}