spring.application.name=aplicacao-principal
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${SERVER_PORT:8080}


# =========================================================
# SWAGGER
# =========================================================

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# =========================================================
# SERVICO DE MOVIMENTACAO
# =========================================================

servico.movimentacao.url=${SERVICO_COMUNICACAO_URL:http://localhost:8081}

spring.cloud.openfeign.client.config.movimentacao-service.connect-timeout=${FEIGN_CONNECT_TIMEOUT:2000}
spring.cloud.openfeign.client.config.movimentacao-service.read-timeout=${FEIGN_READ_TIMEOUT:3000}


# =========================================================
# RABBITMQ
# =========================================================

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

rabbitmq.queue.solicitar-processamento=solicitar.processamento


# =========================================================
# SPRING BATCH
# =========================================================

spring.batch.job.enabled=false

spring.batch.jdbc.initialize-schema=always


# =========================================================
# H2 - SOMENTE METADADOS DO SPRING BATCH
# =========================================================
spring.batch.datasource.jdbc-url=jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.batch.datasource.username=sa
spring.batch.datasource.password=
spring.batch.datasource.driver-class-name=org.h2.Driver