spring.application.name=aplicacao-principal
server.port=8080

spring.datasource.url=jdbc:h2:mem:estoque_principal
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Endereço externo configurável do serviço de movimentação.
servico.movimentacao.url=http://localhost:8081

# OpenFeign
spring.cloud.openfeign.client.config.movimentacao-service.connect-timeout=2000
spring.cloud.openfeign.client.config.movimentacao-service.read-timeout=3000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
